### PR TITLE
npm audit fixes

### PR DESCRIPTION
**Pull request by mikeplem**
- had to add the overrides block to package.json as `npm audit fix` didn't do anything

### CODE REVIEW

**Comment by alessbelli** [comment]
This is slightly sus - a major upgrade to a library that doesn't sound like we should need it as an override, what's the path here?

**Comment by mikeplem** [comment]
> This is slightly sus - a major upgrade to a library that doesn't sound like we should need it as an override, what's the path here?

The override is because `npm audit fix` did not do anything, so I forced the upgrade by using the override block.

The `uglify-js` library is a dependency of a dependency. The script continues to work correctly after the update but that doesn't answer why it is needed but I am not in a position at this time to rewrite this code to do work differently.

**Comment by mikeplem** [comment]
> This is slightly sus - a major upgrade to a library that doesn't sound like we should need it as an override, what's the path here?

You have prompted me to look into this more and I now wonder if we need the library at all.  `require` uses `uglify-js` but i wonder if `require` is needed.

**Comment by mikeplem** [comment]
@alessbelli turns out `require` is not needed so I removed it and that gets rid of `uglify-js`

**Review by Robert-W — APPROVED** [review]

**Pull request merged**
